icn_platform_home:
    path:    /{page}
    defaults:
        _controller: ICNPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

icn_platform_view:
    path:    /advert/{id}
    defaults: { _controller: ICNPlatformBundle:Advert:view }
    requirements:
        id: \d+

icn_platform_add:
    path:    /add
    defaults: { _controller: ICNPlatformBundle:Advert:add }

icn_platform_edit:
    path: /edit/{id}
    defaults: { _controller: ICNPlatformBundle:Advert:edit }
    requirements:
        id: \d+

icn_platform_delete:
    path: /delete/{id}
    defaults: { _controller: ICNPlatformBundle:Advert:delete }
    requirements:
        id: \d+